#ifndef ADBCAT_ADBCAT_H
#define ADBCAT_ADBCAT_H

#define DEFAULT_GATEWAY_PORT "42821"
#define DEFAULT_GATEWAY_HOST "adbcat.frazieje.com"
#define DEFAULT_LOCAL_LISTEN_PORT "5038"
#define DEFAULT_ADB_SERVER_PORT "5037"

#define SESSION_KEY_SIZE 16
#define MAGIC_BYTES_SIZE 8
#define SESSION_TYPE_SIZE 6
#define SESSION_TYPE_SERVER "SERVER"
#define SESSION_TYPE_CLIENT "CLIENT"
#define SESSION_OK_RESPONSE "OK "
#define SESSION_OK_RESPONSE_SIZE 3
#define SERVER_CLOSE_MSG "CLOSE"
#define SERVER_FWD_MSG "FWARD"
#define SERVER_MSG_SIZE 5
#define SERVER_FWD_FROM_SIZE 4
#define SERVER_FWD_LENGTH_SIZE 8

#define MAX_INPUT_BUFFER_SIZE (512*1024)
#define MAX_OUTPUT_BUFFER_SIZE (512*1024)

static unsigned char MAGIC_BYTES[] = { 15, 7, 20, 1, 3, 2, 4, 1};
static unsigned char EMPTY_SESSION[SESSION_KEY_SIZE];

enum adbcat_type { gateway, client, server };

#endif //ADBCAT_ADBCAT_H
